// src/utils/taskSuggestions.js
const predefinedSuggestions = [
  "Write a report",
  "Fix login bug",
  "Buy groceries",
  "Plan meeting",
  "Review PR",
  "Study React",
  "Finish project",
  "Call doctor",
  "Pay bills",
  "Backup files",
  "Update resume",
  "Submit timesheet",
  "Clean workspace",
  "Prepare presentation",
  "Respond to emails",
  "Organize files",
  "Attend team meeting",
  "Research competitors",
  "Refactor old code",
  "Write documentation",
  "Practice coding problems",
  "Update portfolio website",
  "Check server status",
  "Test new feature",
  "Optimize database",
  "Fix CSS issues",
  "Push changes to Git",
  "Create GitHub issue",
  "Plan sprint tasks",
  "Deploy to staging",
  "Write unit tests",
  "Review analytics",
  "Write blog post",
  "Schedule social media",
  "Create wireframes",
  "Read tech article",
  "Learn TypeScript",
  "Watch tutorial",
  "Update dependencies",
  "Clean browser cache",
  "Create new branch",
  "Merge pull request",
  "Book appointment",
  "Water plants",
  "Refill groceries",
  "Change passwords",
  "Create budget plan",
  "Schedule a workout",
  "Call family",
  "Meditate",
  "Read a chapter",
  "Check notifications",
  "Update calendar",
  "Clear inbox",
  "Organize bookmarks",
  "Submit application",
  "Write feedback",
  "Export database backup",
  "Check for updates"
];

export default predefinedSuggestions;
